version: '3.4'
services:
  
  pdspi-mapper-parallex-example:
    build:
      context: .
    restart: always
#   environment:
#       LOG_LEVEL: DEBUG
    ports:
      - $API_PORT:8080
    volumes:
      - ./config:/usr/src/app/config

networks:                      
  default:                     
    driver: bridge             
    ipam:                      
      driver: default          
      config:                  
        - subnet: 172.18.1.0/24
    
